default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint code
        language: system
        entry: make
        args: ["lint"]
        always_run: true
        pass_filenames: false
      - id: test
        name: test code
        language: system
        entry: maek
        args: ["test"]
        always_run: true
        pass_filenames: false
