default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: isort-black-pylint-flake8
        name: lint code
        language: system
        entry: bash -c "make lint"
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: test code
        language: system
        entry: bash -c "make test"
        always_run: true
        pass_filenames: false
